base: /
languages:
  -
    title: English
    enabled: true
    locale: en-US
    hreflang: ''
    base: /
    websiteTitle: ''
    navigationTitle: ''
    flag: us
    languageId: 0
  -
    title: German
    enabled: true
    locale: de_DE
    hreflang: ''
    base: /de/
    websiteTitle: ''
    navigationTitle: Deutsch
    fallbackType: strict
    fallbacks: ''
    flag: de
    languageId: 1
rootPageId: 13
websiteTitle: ''
