base: "https://sascha-nabrotzky.de.ddev.site/"
languages:
    - title: English
      enabled: true
      languageId: 1
      base: /en/
      locale: en_US.UTF-8
      navigationTitle: English
      flag: us
      hreflang: ""
      websiteTitle: ""
    - title: German
      enabled: true
      locale: de_DE
      hreflang: ""
      base: /
      websiteTitle: ""
      navigationTitle: Deutsch
      fallbackType: strict
      fallbacks: ""
      flag: de
      languageId: 0
rootPageId: 1
websiteTitle: "Sascha Nabrotzky | Illustrator"
